source 'https://github.com/CocoaPods/Specs.git'
xcodeproj 'Project'

def import_pods
    use_frameworks!
    pod "CDTDatastore", :path => "../"
end

target :ios do
    platform :ios, '7.0'
    link_with 'Project'
    import_pods
end
